dv/dpi/spike_dpi.cc
dv/if/commit_if.sv
dv/env/ref_env_pkg.sv
dv/dpi/spike_dpi_wrapper.sv
hw/rtl/alu.v
hw/rtl/aludec.v
hw/rtl/maindec.v
hw/rtl/control.v
hw/rtl/MemoryByteAddressable/byteEnableDecoder.v
hw/rtl/MemoryByteAddressable/memory_write_first.v
hw/rtl/MemoryByteAddressable/memByteAddressable32WF.v
hw/rtl/MemoryByteAddressable/memReadManager.v
hw/rtl/MemoryByteAddressable/memTopo32LittleEndian.v
hw/rtl/branchControl.v
hw/rtl/extend.v
hw/rtl/mux.v
hw/rtl/mux4.v
hw/rtl/pc.v
hw/rtl/register.v
hw/rtl/registerFile.v
hw/rtl/cpu.v
hw/rtl/cpu_wrapper.sv
sim/riscv_tb_top.sv
